spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhanghongzheng/demo-spring-config-repo
server:
  port: 20000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10010/eureka/

